[theme]
base = "light"
primaryColor = "#0a0a0a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#fafafa"
textColor = "#0a0a0a"
font = "sans serif"

[server]
headless = true
runOnSave = false
fileWatcherType = "auto"
